pipeline {

  environment {
    registry = "spinningops/jenkins"
    dockerImage = ""
  }

  agent { label 'jenkins-agent' }

  stages {

    stage('Checkout Source') {
      steps {

        git branch: "main",
          url: 'git@github.com:spinningops/JenkinsCI.git'
      }
    }

    stage('Install Packer') {
      steps {
        script {

          bash'''#!/bin/bash 
                        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                        sudo apt-get update && sudo apt-get install packer
                    '''
        }
      }
    }

    stage('packer validate') {
      steps {
        script {

          bash'''#!/bin/bash 
                        packer validate
                    '''
        }
      }
    }

    stage('packer build') {
      steps {
        script {

          bash'''#!/bin/bash 
                        packer validate
                        create_jenkins_agent/packer build jenkins-agent-ubuntu-ami.json
                    '''
        }
      }
    }

  }

}