pipeline {

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git branch: "master",
          // credentialsId: 'cfd6c76a-406c-4a8f-af8c-13d907ef0d4b',
          url: 'git@github.com:spinningops/JenkinsCI.git'
      }
    }

    stage('Upload to S3') {
        steps{
            script {

                dir(''){

                    pwd(); //Log current directory

                    withAWS(region:'us-east-1',credentials:'18a9ad57-22ad-4d15-9dda-391bccb8fc13') {

                        def identity=awsIdentity();//Log AWS credentials

                        // Upload files from working directory '' in your project workspace
                        s3Upload(bucket:"website.spinningops.com", workingDir:'', includePathPattern:'**/*');
                    }

                };
            }
        }
    }

  }

}