# change the version for the latest image
FROM jenkins/jenkins:2.296-alpine
# this is to enable hook from GitHub
ENV JAVA_OPTS -Djava.net.preferIPv4Stack=true -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration=false