pipeline {

  environment {
    registry = "spinningops/go-websample"
    dockerImage = ""
  }

  agent any
        

  stages {

    stage('Checkout Source') {
      steps {
        git branch: "main",
          credentialsId: '064af216-d6d6-4932-9e81-6ee83aaf7eb8',
          url: 'git@github.com:spinningops/spinningops-blog.git'
      }
    }


    stage('Build image') {
      steps {
        script {


          dockerImage = docker.build(registry + ":go-websample$BUILD_NUMBER", "-f Golang/go_create_website_stack/Dockerfile .")

        }
      }
    }

    stage('Push Image') {
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', '978cd482-3ecb-49dc-afeb-f485adf161aa' ) {
            dockerImage.push()
                
            }
          }
        }
      }

    stage('Deploy cf stack') {
        steps{
            script {

                dir(''){

                    pwd(); //Log current directory

                    withAWS(region:'us-east-1',credentials:'18a9ad57-22ad-4d15-9dda-391bccb8fc13') {

                        def identity=awsIdentity();//Log AWS credentials

                    steps{

                        sh 'Golang/go_create_website_stack/create_cf_stack.sh'
                    }

                };
            }
        }
      }
    }

  }

}